fix[] bug filter dan sort data jv in admin and member area
orangerdev/sejoli-jv pull request #2
Opened 2023-04-14 06:53 UTC by asdzakky

2023-04-18 04:44 UTC, orangerdev requested changes

2023-04-18 04:44 UTC, orangerdev commented on json/jv.php
> +            if($post_data['user_id'] > 0) :
ini tambahin jadi intval($post_data['user_id']) ya mas

2023-04-18 04:44 UTC, orangerdev commented on json/jv.php
> +                unset($post_data['backend'], $post_data['nonce']);
ini jadinya redundant, unset($post_data['backend'], $post_data['nonce']) nya di luar conditonal saja

2023-04-18 04:44 UTC, orangerdev commented on json/jv.php
> +                unset($post_data['backend'], $post_data['nonce'], $post_data['user_id']);
ini cukup unset($post_data['user_id'])

2023-04-18 04:44 UTC, orangerdev commented on json/jv.php
disini tambahin unset($post_data['backend'], $post_data['nonce])

2023-04-18 04:44 UTC, orangerdev commented on json/jv.php
> +                'typess'
ini gak salah mas?

2023-04-18 06:07 UTC, asdzakky commented on json/jv.php
> +            if($post_data['user_id'] > 0) :
ok pak

2023-06-15 10:38 UTC, orangerdev approved these changes

2023-06-15 10:38 UTC, merged